resource_group = "Terraform Deployment Project"
location = "South Central US"
vnet_name = "myVNet"
vnet_address_space = ["10.0.0.0/16"]
subnet_names = ["subnet1", "subnet2"]
subnet_prefixes = ["10.0.1.0/24", "10.0.2.0/24"]
vm_name = "myVM"
vm_size = "Standard_B1s"
admin_username = "azureuser"
admin_password = "P@ssw0rd1234!"
